# Generated by Django 4.0 on 2021-12-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('launched_on', models.DateField()),
                ('vegan_available', models.BooleanField()),
                ('location', models.TextField()),
                ('limited_edition', models.BooleanField()),
                ('customers', models.PositiveBigIntegerField()),
            ],
        ),
    ]
