# Generated by Django 4.0 on 2021-12-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IceCreams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavours',
            new_name='Flavour',
        ),
    ]
