# Generated by Django 4.0 on 2022-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IceCreams', '0002_rename_flavours_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='id',
        ),
        migrations.AddField(
            model_name='flavour',
            name='srno',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
