# Generated by Django 4.0 on 2022-01-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IceCreams', '0004_alter_flavour_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='srno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
