# Generated by Django 4.0 on 2022-01-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IceCreams', '0007_remove_flavour_srno_flavour_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='id',
        ),
        migrations.AddField(
            model_name='flavour',
            name='srno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
